import base64
import streamlit as st
import os

# Set the page configuration for the Streamlit app, including title and layout style
st.set_page_config(
    page_title="SABTA – Interview Practice Platform",
    layout="wide"
)

# Sabta logo generated by ChatGPT using the following prompt:
# "Generate a logo for a consulting interview preparation platform called 'SABTA'. The logo should be modern, professional, and also have some details. Use a color palette that includes blue."
# OpenAI. (2025). ChatGPT (Version 4.o) [Large language model]. https://chatgpt.com
st.logo("data/sabta_logo.png", size="large")

# File decoding method generated by ChatGPT using the following prompt:
# "How can I center the logo in the center and adjust the size?."
# OpenAI. (2025). ChatGPT (Version 4.o) [Large language model]. https://chatgpt.com
logo_path = os.path.join(os.path.dirname(__file__), "data", "sabta_logo.png")

# Check if the logo file exists before attempting to read and display it
if os.path.isfile(logo_path):
    # Read the logo image file as bytes
    logo_bytes = open(logo_path, "rb").read()
    # Encode the image bytes to base64 string for embedding in HTML
    logo_b64 = base64.b64encode(logo_bytes).decode()
    # Define an HTML block to center the logo and add a heading below it
    html_header = f"""
    <div style="text-align:center; margin-bottom:30px;">
      <img src="data:image/png;base64,{logo_b64}" width="300" style="margin-bottom:0px;" />
      <h1 font-size:2rem;">Interview Prep Platform & Machine Learning</h1>
    </div>
    """
    # Render the HTML block in the Streamlit app, allowing raw HTML usage
    st.markdown(html_header, unsafe_allow_html=True)
else:
    # Show a warning message if the logo file is not found
    st.warning("Logo 'sabta_logo.png' not found.")

# Add a visual divider line in the app for separation of content
st.divider()

st.write(
    "This application helps **students prepare for case interviews** through comprehensive guides and interactive practice. "
    "Navigate using the pages in the sidebar: **Case Prep** for frameworks and tips, **Drills** for timed practice, and **Sparring** for a rapid Q&A simulation. "
    "Use this platform to improve your structuring, math, reasoning, and communication skills in a case interview setting."
)

# Embed our 4min Video

# Stock video footage created on Artlist
# Artlist. (2025). AI Image & Video [Video Software]. https://artlist.io/image-to-video-ai

# Voice-over created on Artlist
# Artlist. (2025). AI Image & Video [Audio Software]. https://artlist.io/voice-over
st.video("https://www.youtube.com/watch?v=TGstX2uJddQ")

# Problem statement and use case coded in sperate HTML file for better styling and then embedded
with st.container():
    st.markdown(
        """
        <div style="padding: 20px; border: 2px solid #4A90E2; border-radius: 10px; background-color: #F5F9FF;">
            <h2 style="color: #4A90E2; text-align: center; margin-bottom: 15px;">Clearly Defined Problem & Use Case</h2>
            <p style="font-size: 15px; line-height: 1.6; margin: 8px 0;">
                As students navigating the challenging world of consulting and finance, our team faced a common yet daunting problem: preparation for case interviews is overwhelmingly fragmented. With resources scattered across countless websites, PDF guides, forums, and books, preparation often felt disjointed, chaotic, and inefficient. There was no single platfrom where we could find refresh all of the relevant things, given the lack of time and the high stakes of the interviews.
            </p>
            <p style="font-size: 15px; line-height: 1.6; margin: 8px 0;">
                We repeatedly experienced the frustration of losing crucial preparation time simply switching between various sources and tools—this wasn’t just inconvenient; it significantly impacted our confidence and readiness. Interviews are stressful enough, and the lack of a cohesive, integrated preparation platform magnified that anxiety.
            </p>
            <p style="font-size: 15px; line-height: 1.6; margin: 8px 0;">
                After collectively attending over 60 interviews, we realized a critical gap existed in accessible, integrated, and genuinely effective interview preparation. Out of necessity and personal ambition, we decided to build the solution we wished we had from day one.
            </p>
            <h3 style="color: #4A90E2; margin-top: 20px;">Our Comprehensive Solution</h3>
            <p style="font-size: 15px; line-height: 1.6; margin: 8px 0;">
                This platform unites every essential element into one intuitive interface:
                guided frameworks, timed math drills, real data analytics, and interactive
                sparring, simulating the real interview.
            </p>
            <p style="font-size: 15px; line-height: 1.6; margin: 8px 0;">
                Students can go from learning the core concepts to practicing
                under pressure, reviewing analytics on their performance, and sharpening
                their communication skills with a simulated partner.
            </p>
            <h3 style="color: #4A90E2; margin-top: 20px;">Key Features at a Glance</h3>
            <ul style="font-size: 15px; line-height: 1.6;">
                <li><strong>Interview Preperation:</strong> Structured frameworks, interactive hints, and real-world examples.</li>
                <li><strong>Math Drills:</strong> Timed questions across four difficulty levels to build speed and accuracy.</li>
                <li><strong>Math Coach – ML:</strong> Personalized feedback and ML-driven recommendations for optimal practice.</li>
                <li><strong>Finance Analytics – ML:</strong> Live market data, chart tools, and scenario simulations.</li>
                <li><strong>Interview Sparring:</strong> Peer-modeled Q&A rounds for live feedback and scoring.</li>
            </ul>
            <h3 style="color: #4A90E2; margin-top: 20px;">Why It Matters</h3>
            <p style="font-size: 15px; line-height: 1.6; margin: 8px 0;">
                By centralizing all interview prep tools, students regain control and clarity—
                fostering confidence, reducing anxiety, and dramatically improving outcomes.
            </p>
            <p style="font-size: 15px; line-height: 1.6; margin: 8px 0;">
                This platform is not just a tool; it’s a game-changer for students
                determined to excel in their interviews and secure their dream roles.
            </p>
            <h3 style="color: #4A90E2; margin-top: 20px;">About Our Team</h3>
            <p style="font-size: 15px; line-height: 1.6; margin: 8px 0;">
                Built by four friends who collectively completed 60+ interviews at top firms,
                we’ve distilled years of firsthand experience into this platform. Every line of
                code, chart, and question reflects our own journey and rigorous research.
            </p>
            <p style="font-size: 15px; line-height: 1.6; margin: 8px 0;">
                Our goal: empower every candidate to feel prepared, supported, and ready to
                excel—no matter how complex the case or tight the schedule.
            </p>
        </div>
        """,
        unsafe_allow_html=True
    )
