# Question Bank generated by ChatGPT using the following prompt:
# "Generate a list of 5 questions for each of the following categories: Business - Basic, Business - Advanced, Economics - Basic, Economics - Advanced, Finance - Basic, Finance - Advanced, Brain Teasers, Punches, Personal Fit - CV, Personal Fit - Why, Personal Fit - Situations, Personal Fit - Tricky. The questions should be suitable for a consulting interview preparation."
# OpenAI. (2025). ChatGPT (Version 4.o) [Large language model]. https://chatgpt.com

drill_questions = {
   "Basic Math": None,  # handled via function
    "Real World Math": [
        ("5% of $1,000 after 1 year?", 1050),
        ("Profit margin: revenue $500, profit $100 (%)?", "20%"),
        ("Breakeven: $1,000 fixed, $50/unit profit. Units?", 20),
    ],
    "Logical Reasoning": [
        ("If A>B and B>C, is A>C? (True/False)", "True"),
        ("All cats are mammals; Rex is a mammal. Rex is a cat? (T/F/Cannot Say)", "Cannot Say"),
    ],
    "Numerical Reasoning": [
        ("5 pens cost $15. 8 pens cost?", 24),
        ("120 students, 55% male. Females?", 54),
    ],
}
